apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVVOWldDT1M1RktMRkI2NkE=
  AWS_SECRET_ACCESS_KEY: dFd3aWlmWDZsMmkBVm5TanhiNDI2NjlxMnRWbzVuUE0xelVP



