name: Continuous Integration
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev, main ]
jobs:
  build:
    name: Execute Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: './api/package-lock.json'
      - run: npm ci
        working-directory: './api'
      - run: npm run build --if-present
        working-directory: './api'

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'
    - run: npm install
      working-directory: './api'
    - run: npm test
      working-directory: './api'